### PR TITLE
Performance enchantment and fixes

### PR DESCRIPTION
**Pull request by LaTueur**
I found the original script way too slow.
One of the reasons was using self.start.submissions() multiple times.
This especially affected the Submissions class, for this the new script is four times faster.
Along the way multiple bugs were fixed.

### CODE REVIEW

**Review by umitkaanusta — CHANGES_REQUESTED** [review]
If we create a Redditor Node with username [deleted], then every comment with a deleted author will be linked to a Node with username [deleted]. This may be acceptable for a SQL database but in a Graph database, this would be redundant and misleading. (It would simply manipulate centrality metrics, or visualizations where node size is proportional to the number of submissions/comments)

Therefore it'd be better if the data_models.py remains unchanged.

**Comment by LaTueur** [comment]
> If we create a Redditor Node with username [deleted], then every comment with a deleted author will be linked to a Node with username [deleted]. This may be acceptable for a SQL database but in a Graph database, this would be redundant and misleading. (It would simply manipulate centrality metrics, or visualizations where node size is proportional to the number of submissions/comments)
> 
> Therefore it'd be better if the data_models.py remains unchanged.

The main problem is that without this change suspended users throw errors (self.resp.author.name and self.resp.author.id don't work with deleted user). While I have to agree, this can be misleading in the graph. Another approach could be not linking any Redditor to them, but then we entirely discard the information that it was created by a deleted user, and the graph can look incomplete.

**Comment by umitkaanusta** [comment]
> The main problem is that without this change suspended users throw errors (self.resp.author.name and self.resp.author.id don't work with deleted user). While I have to agree, this can be misleading in the graph. Another approach could be not linking any Redditor to them, but then we entirely discard the information that it was created by a deleted user, and the graph can look incomplete.

So we have 2 options:
1. Add a property author_suspended to Comment and Submission nodes (This causes redundancy, we don't need such a property to check if a comment/submission has an author in Neo4j.)
2. If author is suspended, let the graph be incomplete. It would take 1 sentence in the documentation to inform user that if a Submission/Comment's author is not shown, then its author is a deleted/suspended user.

Option 2 looks better: 
- Less nodes and relationships (will do better at scale)
- Less misleading (because of the reasons above)
- Such a specific library's users are proficient enough to read the documentation and work according to that decision. If they still want to add a Redditor Node with username [deleted] for some reason, they can still do it by writing some Cypher code.

**Comment by LaTueur** [comment]
> > So we have 2 options:
> 
> 1. Add a property author_suspended to Comment and Submission nodes (This causes redundancy, we don't need such a property to check if a comment/submission has an author in Neo4j.)
> 2. If author is suspended, let the graph be incomplete. It would take 1 sentence in the documentation to inform user that if a Submission/Comment's author is not shown, then its author is a deleted/suspended user.
> 
> Option 2 looks better:
> 
> * Less nodes and relationships (will do better at scale)
> * Less misleading (because of the reasons above)
> * Such a specific library's users are proficient enough to read the documentation and work according to that decision. If they still want to add a Redditor Node with username [deleted] for some reason, they can still do it by writing some Cypher code.

Pushed a fix implementing Option 2.

**Comment by umitkaanusta** [comment]
That's pretty cool, can you also add/edit tests in compliance with the new changes? After that I'll merge

**Comment by LaTueur** [comment]
> That's pretty cool, can you also add/edit tests in compliance with the new changes? After that I'll merge

Okay it's done. I'm not sure if there are any other possible tests, only these came up in my mind.

**Review by umitkaanusta — APPROVED** [review]

**Pull request merged**
